// generators/attendance/instructionsSheet.js
// Generates the instructions sheet XML for the shift tracker
import { escapeXml } from '../../core/index.js';
import { STYLE_IDS } from '../../../presentation/index.js';
import { createInstructionColumns, generateColumnsXML, generateRowXML, ROW_HEIGHTS } from '../../../presentation/sizing/excelSizing.js';

// Debug: Track successful imports and module loading
console.log('✓ AttendanceInstructions imports loaded:', {
  escapeXml: typeof escapeXml,
  STYLE_IDS: typeof STYLE_IDS,
  createInstructionColumns: typeof createInstructionColumns,
  generateColumnsXML: typeof generateColumnsXML,
  generateRowXML: typeof generateRowXML,
  ROW_HEIGHTS: typeof ROW_HEIGHTS
});

export function buildInstructionsSheet() {
  console.log('📋 AttendanceInstructions: Building instructions sheet...');
  const instructions = [
    'EMPLOYEE SHIFT TRACKER - INSTRUCTIONS',
    '',
    '1. MAIN TRACKER SHEET:',
    '   • Enter daily hours worked in the Monday-Sunday columns',
    '   • Use decimal format (e.g., 8.5 for 8 hours 30 minutes)',
    '   • Leave blank for days not worked',
    '   • Total hours will calculate automatically',
    '',
    '2. QUICK REFERENCE SHEET:',
    '   • Shows each employee\'s assigned shift times',
    '   • Use this to verify correct scheduling',
    '   • Includes employee contact information',
    '',
    '3. TIPS FOR MANAGERS:',
    '   • Save this file to keep your data',
    '   • Print the tracker for manual time entry',
    '   • Use conditional formatting to highlight overtime',
    '   • Back up your data regularly',
    '   • Share the Quick Reference with supervisors',
    '',
    '4. FORMULAS INCLUDED:',
    '   • Weekly totals automatically calculated',
    '   • Easy to add additional calculations',
    '   • Compatible with payroll systems',
    '',
    'Generated by Employee Shift Tracker App',
    'www.freeexcelgenerator.com'
  ];
  const columnDefs = createInstructionColumns();
  const colsXML = generateColumnsXML(columnDefs);
    let rowsXML = '';
  instructions.forEach((instruction, index) => {
    const rowNum = index + 1;
    const isTitle = index === 0;
    const isHeader = instruction.match(/^\d+\./);
    const isEmpty = instruction === '';      let styleId = STYLE_IDS.INSTRUCTION_BULLET; // Default text style
    if (isTitle) styleId = STYLE_IDS.INSTRUCTION_TITLE; // Use title style for main title
    else if (isHeader) styleId = STYLE_IDS.INSTRUCTION_SECTION_HEADER; // Section header style
    
    // Use universal height constants with auto-height option
    let heightType = 'instruction';
    let enableAutoHeight = true; // Default to auto-height for text content
    if (isEmpty) {
      heightType = 'spacer';
      enableAutoHeight = false; // Fixed height for spacers
    } else if (isTitle) {
      heightType = 'title';
      enableAutoHeight = false; // Fixed height for titles
    } else if (isHeader) {
      heightType = 'header';
      enableAutoHeight = false; // Fixed height for headers
    }
      // Use generateRowXML for consistent row generation
    const rowStartXML = generateRowXML(rowNum, heightType, {
      styleId,
      enableAutoHeight
    });
    
    rowsXML += rowStartXML;
    rowsXML += `<c r="A${rowNum}" s="${styleId}" t="inlineStr"><is><t>${escapeXml(instruction)}</t></is></c>`;
    rowsXML += '</row>';
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  ${colsXML}
  <sheetData>
    ${rowsXML}
  </sheetData>
</worksheet>`;
}