// generators/attendance/instructionsSheet.js
// Generates the instructions sheet XML for the shift tracker
import { escapeXml } from '../../core/index.js';
import { STYLE_IDS } from '../../../presentation/index.js';
import { createInstructionColumns, generateColumnsXML, generateRowXML, ROW_HEIGHTS } from '../../../presentation/sizing/excelSizing.js';

// Debug logs removed

export function buildInstructionsSheet() {
  // Debug logs removed
  const instructions = [
    'EMPLOYEE SHIFT TRACKER - INSTRUCTIONS',
    '',
    '1. MAIN TRACKER SHEET:',
    '   • Enter daily hours worked in the Monday-Sunday columns',
    '   • Use decimal format (e.g., 8.5 for 8 hours 30 minutes)',
    '   • Leave blank for days not worked',
    '   • Total hours will calculate automatically',
    '   • Use the legend dropdown for status tracking',
    '',
    '2. LEGEND SYSTEM:',
    '   • Custom status options for each day (Present, Absent, Holiday, etc.)',
    '   • Data validation ensures consistent entry',
    '   • Dropdown menus prevent typing errors',
    '   • Color-coded for visual clarity',
    '',
    '3. QUICK REFERENCE SHEET:',
    '   • Shows each employee\'s assigned shift times and contact info',
    '   • Legend Usage Analytics with dynamic formulas',
    '   • Real-time tracking of status usage patterns',
    '   • Percentage calculations update automatically',
    '',
    '4. LEGENDS SHEET:',
    '   • Centralized legend definitions with color coding',
    '   • Used for data validation across all sheets',
    '   • Modify here to update dropdown options',
    '',
    '5. ADVANCED FEATURES:',
    '   • Conditional formatting highlights important data',
    '   • Data validation prevents invalid entries',
    '   • Dynamic date ranges adapt to different months',
    '   • Merged cells for clean presentation',
    '   • Proper column sizing for readability',
    '',
    '6. FORMULAS INCLUDED:',
    '   • Weekly totals automatically calculated',
    '   • Legend usage counting with COUNTIF functions',
    '   • Percentage calculations for analytics',
    '   • Cross-sheet references for data consistency',
    '',
    '7. TIPS FOR MANAGERS:',
    '   • Save this file to keep your data',
    '   • Print the tracker for manual time entry',
    '   • Use legend analytics to identify patterns',
    '   • Back up your data regularly',
    '   • Share the Quick Reference with supervisors',
    '',
    '8. DATA VALIDATION:',
    '   • Legend columns have dropdown validation',
    '   • Only valid options can be selected',
    '   • Reduces data entry errors',
    '   • Maintains data consistency',
    '',
    'Generated by Employee Shift Tracker App',
    'Advanced Excel Generator with OOXML Technology'
  ];
  const columnDefs = createInstructionColumns();
  const colsXML = generateColumnsXML(columnDefs);
    let rowsXML = '';
  instructions.forEach((instruction, index) => {
    const rowNum = index + 1;
    const isTitle = index === 0;
    const isHeader = instruction.match(/^\d+\./);
    const isEmpty = instruction === '';
    const isFooter = index >= instructions.length - 2; // Last two lines are footers
    let styleId = STYLE_IDS.INSTRUCTION_BULLET; // Default text style
    if (isTitle) styleId = STYLE_IDS.INSTRUCTION_TITLE; // Use title style for main title
    else if (isHeader) styleId = STYLE_IDS.INSTRUCTION_SECTION_HEADER; // Section header style
    else if (isFooter) styleId = STYLE_IDS.INSTRUCTION_FOOTER; // Footer style for last two lines
    // Use universal height constants with auto-height option
    let heightType = 'instruction';
    let enableAutoHeight = true; // Default to auto-height for text content
    if (isEmpty) {
      heightType = 'spacer';
      enableAutoHeight = false; // Fixed height for spacers
    } else if (isTitle) {
      heightType = 'title';
      enableAutoHeight = false; // Fixed height for titles
    } else if (isHeader) {
      heightType = 'header';
      enableAutoHeight = false; // Fixed height for headers
    } else if (isFooter) {
      heightType = 'footer';
      enableAutoHeight = false; // Fixed height for footers
    }
    // Use generateRowXML for consistent row generation
    const rowStartXML = generateRowXML(rowNum, heightType, {
      styleId,
      enableAutoHeight
    });
    rowsXML += rowStartXML;
    rowsXML += `<c r="A${rowNum}" s="${styleId}" t="inlineStr"><is><t>${escapeXml(instruction)}</t></is></c>`;
    rowsXML += '</row>';
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  ${colsXML}
  <sheetData>
    ${rowsXML}
  </sheetData>
</worksheet>`;
}