// generators/contentTypesXml.js
// Generates [Content_Types].xml and rels for Excel

export function getContentTypesXML(includeTracker) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  ${includeTracker ? `<Override PartName="/xl/worksheets/sheet3.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>` : ''}
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>`;
}

export function getRelsXML() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`;
}

export function getSheet1InstructionsXML() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <cols><col min="1" max="8" width="15"/></cols>
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr" s="4"><is><t>📅 How to Use This Smart Calendar Workbook</t></is></c>
      <c r="B1" s="4"></c>
      <c r="C1" s="4"></c>
      <c r="D1" s="4"></c>
      <c r="E1" s="4"></c>
      <c r="F1" s="4"></c>
      <c r="G1" s="4"></c>
      <c r="H1" s="4"></c>
    </row>
    <row r="2"><c r="A2" t="inlineStr" s="5"><is><t>🎉 This Excel workbook was generated by Free Excel Generators with advanced conditional formatting!

✨ Smart Features:
📝 Enter custom values in the Legend column (right side)
🎨 Type matching text in calendar cells - they auto-highlight with legend colors!
📊 Optional Tracker sheet automatically counts your entries
📱 Works perfectly in Excel, Google Sheets, and other spreadsheet apps

🚀 Quick Start:
1️⃣ Replace "Enter Value Here" in Legend with your own labels (Gym, Meeting, Holiday, etc.)
2️⃣ Type those same labels in calendar event cells
3️⃣ Watch the magic - cells automatically highlight with matching colors!
4️⃣ Check the Tracker sheet (if included) for automatic counting

💡 Pro Tip: Text matching is case-insensitive (gym = Gym = GYM)

🌐 www.freeexcelgenerator.com</t></is></c></row>
  </sheetData>
  <mergeCells count="2"><mergeCell ref="A1:H1"/><mergeCell ref="A2:H25"/></mergeCells>
</worksheet>`;
}

// All logic for getContentTypesXML, getRelsXML, and getSheet1InstructionsXML matches script.js, including tracker support and XML structure.
// No changes needed.
