// generators/calendar/instructionsSheet.js
// Generates the instructions worksheet XML for the calendar
import { escapeXml } from '../../core/index.js';
import { STYLE_IDS } from '../../../presentation/index.js';
import { createInstructionColumns, generateColumnsXML, generateRowXML, ROW_HEIGHTS } from '../../../presentation/sizing/excelSizing.js';

// Debug: Track successful imports and module loading
console.log('✓ InstructionsSheet imports loaded:', {
  escapeXml: typeof escapeXml,
  STYLE_IDS: typeof STYLE_IDS,
  createInstructionColumns: typeof createInstructionColumns,
  generateColumnsXML: typeof generateColumnsXML,
  generateRowXML: typeof generateRowXML,
  ROW_HEIGHTS: typeof ROW_HEIGHTS
});

export function getSheet1InstructionsXML() {
  console.log('📋 InstructionsSheet: Generating instructions sheet...');
  const instructions = [
    'SMART CALENDAR WORKBOOK - INSTRUCTIONS',
    '',
    '1. CALENDAR SHEET:',
    '   • Enter events in the calendar cells below each date',
    '   • Type exactly as shown in the Legend for auto-highlighting',
    '   • Text matching is case-insensitive (gym = Gym = GYM)',
    '   • Multiple events per day are supported',
    '',
    '2. LEGEND CUSTOMIZATION:',
    '   • Replace "Enter Value Here" with your own labels',
    '   • Examples: Meeting, Gym, Appointment, Holiday, Travel',
    '   • Colors will automatically highlight matching text',
    '   • Up to 9 different categories supported',
    '',
    '3. SMART FEATURES:',
    '   • Conditional formatting automatically colors matching text',
    '   • Works in Excel, Google Sheets, and other spreadsheet apps',
    '   • Professional formatting with merged cells and styling',
    '   • Optional tracker sheet counts your entries automatically',
    '',
    '4. QUICK START GUIDE:',
    '   • Step 1: Customize legend values on the right side',
    '   • Step 2: Type those same values in calendar cells',
    '   • Step 3: Watch cells automatically highlight with legend colors',
    '   • Step 4: Check tracker sheet (if included) for automatic counts',
    '',
    '5. TIPS FOR BEST RESULTS:',
    '   • Keep legend entries short and descriptive',
    '   • Use consistent spelling for automatic highlighting',
    '   • Save file regularly to preserve your data',
    '   • Print calendar for offline reference',
    '   • Share with team members for collaborative planning',
    '',
    '6. TECHNICAL FEATURES:',
    '   • Advanced conditional formatting with Excel formulas',
    '   • Optimized for both digital and print use',
    '   • Compatible with Excel 2016+ and Google Sheets',
    '   • Automatic color coding using UPPER() functions',
    '',
    'Generated by Smart Calendar Builder',
    'www.freeexcelgenerator.com'
  ];  const columnDefs = createInstructionColumns();
  const colsXML = generateColumnsXML(columnDefs, {
    enableAutoWidth: false,
    includeSheetFormat: true
  });
  
  let rowsXML = '';
  instructions.forEach((instruction, index) => {
    const rowNum = index + 1;
    const isTitle = index === 0;
    const isHeader = instruction.match(/^\d+\./);
    const isEmpty = instruction === '';
    const isInstructionHighlight = instruction.startsWith('   •');
    const isFooter = index >= instructions.length - 2; // Last two lines are footers
    let styleId = STYLE_IDS.INSTRUCTION_BULLET; // Default text style
    if (isTitle) {
      styleId = STYLE_IDS.INSTRUCTION_TITLE; // Use title style for main title
    } else if (isHeader) {
      styleId = STYLE_IDS.INSTRUCTION_SECTION_HEADER; // Bold section headers
    } else if (isInstructionHighlight) {
      styleId = STYLE_IDS.INSTRUCTION_HIGHLIGHT; // Highlight style for bullet points
    } else if (isEmpty) {
      styleId = STYLE_IDS.INSTRUCTION_SPACER; // Spacer style for empty rows
    } else if (isFooter) {
      styleId = STYLE_IDS.INSTRUCTION_FOOTER; // Footer style for last two lines
    }
    // Use enhanced row generation with consistent height behavior
    let heightType = 'instruction';
    let enableAutoHeight = true; // Default to auto-height for text content
    if (isEmpty) {
      heightType = 'spacer';
      enableAutoHeight = false; // Fixed height for spacers
    } else if (isTitle) {
      heightType = 'title';
      enableAutoHeight = false; // Fixed height for titles
    } else if (isHeader) {
      heightType = 'header';
      enableAutoHeight = false; // Fixed height for headers
    }
      const rowStartXML = generateRowXML(rowNum, heightType, {
      enableAutoHeight  // Consistent auto-height behavior
    });
    rowsXML += rowStartXML;
    rowsXML += `<c r="A${rowNum}" s="${styleId}" t="inlineStr"><is><t>${escapeXml(instruction)}</t></is></c>`;
    rowsXML += '</row>';
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  ${colsXML}
  <sheetData>
    ${rowsXML}
  </sheetData>
</worksheet>`;
}